"""
parent_relationship.py
────────────────────────
"Grandparent" layer — Tier B of the "chord progression" retrieval design
(see retrieval_layer's expand_siblings/expand_cross_parent for Tier A).

WHAT THIS BUILDS — a pure additive wrapper, nothing else:
  Sub-parents (sub_categories) NEVER move. Each stays exactly where nested.py
  put it, under its original parent, completely unchanged — same fields,
  same topics, same chunks, same qna. Only whole PARENTS get grouped, and
  the grouping is a wrapper ABOVE parents, not a rewrite of anything below:

      {
        "parent_category_name": "<LLM-generated grandparent name>",
        "parent_category_description": "<LLM-generated, from member parents'
                                          OWN existing name+description pairs>",
        "member_parents": [ <full original parent object, verbatim>, ... ]
      }

  This is the exact same recursive pattern nested.py itself already uses one
  level down — a parent's own name+description is generated by feeding its
  sub-categories' name+description pairs to an LLM (nested.py's macro
  naming/description prompts, "Batch 5 & 6"). Here that same prompt shape is
  reused one level up, fed the member PARENTS' own existing
  parent_category_name/parent_category_description — no new schema
  (no key_features/notable_details/connecting_subparents — an earlier
  version of this file invented those; don't reintroduce them).

  Written to a SEPARATE file (parent_relationship_clusters.json), not
  patched into enterprise_nested_topics.json — router index building, both
  summarizers, and chroma ingestion all iterate `taxonomy` as a flat parent
  list and would break if a grandparent level were inserted there.

HOW GROUPING (which parents belong together) IS DECIDED:
  Whole-parent embedding + Louvain, matching nested.py's own MACRO_THRESHOLD
  mechanism directly (not the sub-parent-grounded contraction an earlier
  version of this file used). Each parent is embedded from its name + all
  its own sub-categories' name+description, blended into one vector — the
  same combined_text discipline nested.py itself uses at the topic level,
  applied at the parent level. An earlier version of this file used a more
  surgical sub-parent-level contraction instead (comparing individual
  sub-parents across parent boundaries, only merging parents when a
  specific connecting sub-parent pair justified it) — that produced more
  differentiated, smaller groups, but confirmed-split apart a pairing
  (Healthcare Financial Operations + Healthcare Financial Operations &
  Security) that should stay together. Reverted to whole-parent grouping
  for that reason: it's coarser, but it keeps parents whose OVERALL
  descriptions genuinely overlap in the same group, which is what's wanted
  here more than surgical precision.

  1. Louvain community detection on the full parent-level similarity graph
     (threshold = 0.60, same as nested.py's MACRO_THRESHOLD).
  2. LLM outlier audit per candidate group (nested.py's own "Odd One Out"
     prompt, applied to parent names) — the sole quality gate; no separate
     content-based filter on the generated description.

  "Edge Cases & Standalone Topics" sub-categories are excluded from each
  parent's embedding text — nested.py itself documents these as topics that
  "did not strongly align with other clusters", and including them was
  confirmed to inject generic catch-all phrasing that produced spurious
  matches. This only affects the embedding text used for GROUPING — every
  original sub-category (including edge-case buckets) still appears
  verbatim in the output once its parent is nested in.

Retrieval methodology (router.py / retriever.py) is untouched by this file —
only how this offline knowledge object gets built.
"""

import json
import logging
import re
from typing import Dict, List, Tuple

import networkx as nx
import community.community_louvain as community_louvain
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

import config
import llm_client
from nested import parse_llm_list
from topic_summarizer import _get_domain_profile

logging.basicConfig(level=logging.INFO, format="%(levelname)-8s %(message)s")
log = logging.getLogger(__name__)

NESTED_PATH   = config.NESTED_OUTPUT_PATH
OUT_PATH      = config.OUTPUT_DIR / "parent_relationship_clusters.json"

EMBED_MODEL      = "all-MiniLM-L6-v2"   # matches nested.py exactly
EDGE_CASE_NAME   = "Edge Cases & Standalone Topics"
PARENT_THRESHOLD = 0.60   # matches nested.py's own MACRO_THRESHOLD

# Tried simply lowering this to 0.55 to catch more candidates for the one
# genuine family Louvain finds at 0.60 (50 parents -> 40 stay unplaced: 30 in
# naming-collision blobs the filter correctly drops, 10 true isolates). That
# DID pull in 4 more plausible members pre-audit, but re-running the outlier
# audit on the reshuffled 14-member batch also DROPPED 5 members that were
# previously confirmed genuine at 0.60 (Healthcare System Configuration,
# Healthcare System Operations & Configuration, Healthcare System
# Configuration & Integrity, Healthcare Payer Operations & Configuration,
# Healthcare Data Integrity & Governance) — the LLM's "odd one out" judgment
# is sensitive to what else is in the batch, not just the candidate itself.
# Net change was -3 members, not +4. Reverted the global threshold; see
# _find_affiliates() below for the stable alternative: keep the confirmed
# group frozen, test each unplaced parent against it individually instead of
# re-clustering and re-auditing everything at once.
AFFILIATE_THRESHOLD = 0.55   # lower bar, but only for testing ALREADY-UNPLACED parents against an ALREADY-CONFIRMED group


def _load_parents() -> Tuple[List[Dict], Dict]:
    with open(NESTED_PATH, encoding="utf-8") as f:
        taxonomy_data = json.load(f)

    parents = []
    for idx, p in enumerate(taxonomy_data["taxonomy"]):
        name = p.get("parent_category_name", "")
        subs = p.get("sub_categories", [])
        sub_lines = [
            f"{s.get('sub_category_name','')}: {s.get('sub_category_description','')}"
            for s in subs if s.get("sub_category_name") and s.get("sub_category_name") != EDGE_CASE_NAME
        ]
        parents.append({
            "idx": idx,
            "name": name,
            "combined_text": f"{name}. " + " ".join(sub_lines),
        })
    return parents, taxonomy_data


def _embed_parents(parents: List[Dict]):
    """Parent-level embeddings, computed once and reused for both the
    initial Louvain graph and the later affiliate search."""
    embedder = SentenceTransformer(EMBED_MODEL, device="cpu")
    return embedder.encode([p["combined_text"] for p in parents], show_progress_bar=False)


def _build_parent_graph(embs) -> nx.Graph:
    """Full parent-level similarity graph — mirrors nested.py's own
    macro-graph construction exactly, one level up."""
    sim = cosine_similarity(embs)

    G = nx.Graph()
    G.add_nodes_from(range(len(embs)))
    for i in range(len(sim)):
        for j in range(i + 1, len(sim)):
            if sim[i][j] > PARENT_THRESHOLD:
                G.add_edge(i, j, weight=float(sim[i][j]))
    return G


def _outlier_prompt(names: List[str], analyst_role: str) -> str:
    """Shared 'Odd One Out' prompt nested.py uses — used both to audit a
    freshly-Louvain'd group and, one at a time, to test a single affiliate
    candidate against an already-confirmed group (see _audit_affiliates)."""
    return (
        f"You are {analyst_role}, acting as an expert systems auditor. "
        "I will give you a list of top-level feature-area categories that an "
        "algorithm grouped together as related.\n"
        "Your job is to find the 'Odd One Out' (Outliers). An outlier is a "
        "category that does NOT share the core functional or technical theme "
        "of the rest.\n\n"
        "### Examples:\n"
        "Group:\n1. Claims Processing Workflow\n2. Remittance Advice Management\n"
        "3. Network Security Protocols\n"
        "Outliers: [\"Network Security Protocols\"]\n\n"
        "Group:\n1. Patient Registration\n2. Appointment Scheduling\n"
        "3. Clinical Documentation\n"
        "Outliers: [\"NONE\"]\n\n"
        "### Now evaluate this Group:\n"
        + "\n".join(f"- {n}" for n in names) + "\n\n"
        "Reply EXACTLY with a Python list of the exact category names that are "
        "outliers. If all fit perfectly, reply [\"NONE\"]. Do not add any "
        "conversational text."
    )


def _audit_outliers(clusters: Dict[int, List[int]], parent_names: Dict[int, str], analyst_role: str) -> Dict[int, List[int]]:
    """Same 'Odd One Out' prompt nested.py uses, applied to parent membership
    within a grandparent group."""
    multi = {cid: members for cid, members in clusters.items() if len(members) > 1}
    if not multi:
        return clusters

    cluster_ids = list(multi.keys())
    prompts = [_outlier_prompt([parent_names[m] for m in multi[cid]], analyst_role) for cid in cluster_ids]

    log.info(f"Auditing {len(prompts)} multi-member grandparent group(s) for outliers...")
    responses = llm_client.generate_batch(prompts, max_tokens=80, desc="Grandparent outlier audit")

    cleaned: Dict[int, List[int]] = dict(clusters)
    next_singleton_id = max(clusters.keys(), default=0) + 1000
    for cid, raw in zip(cluster_ids, responses):
        outlier_names = set(parse_llm_list(raw))
        if not outlier_names or outlier_names == {"NONE"}:
            continue
        kept, removed = [], []
        for m in multi[cid]:
            (removed if parent_names[m] in outlier_names else kept).append(m)
        if removed:
            log.info(f"Group {cid}: removed outlier(s) {[parent_names[m] for m in removed]}")
            cleaned[cid] = kept
            for m in removed:
                cleaned[next_singleton_id] = [m]
                next_singleton_id += 1
    return cleaned


def _find_affiliate_candidates(embs, genuine: Dict[int, List[int]], placed_ids: set) -> Dict[int, List[int]]:
    """Louvain at PARENT_THRESHOLD only ever surfaces ONE global partition —
    it can't tell you "this specific unplaced parent has a real, if weaker,
    connection to an already-confirmed group" because a single cross edge
    gets outweighed by whatever community that parent's OTHER edges pull it
    toward (or it has no edge at all above 0.60). This checks it directly:
    for every parent not already in a confirmed group — true isolates AND
    members of the dropped naming-collision blobs alike, since being in a
    junk blob with its same-named siblings doesn't rule out a real link to a
    different family — compare it to each confirmed group's centroid at a
    lower bar (0.55). Candidates that clear it go to _audit_affiliates for
    the actual accept/reject decision; this step only narrows the field."""
    n = embs.shape[0]
    unplaced = [i for i in range(n) if i not in placed_ids]
    candidates: Dict[int, List[int]] = {}
    if not unplaced:
        # Nothing left to find an affiliation for — small corpora (few parent
        # topics) can genuinely place every parent in the first pass, which
        # larger corpora may never hit. cosine_similarity rejects an empty
        # array, so this must return early rather than call it below.
        return candidates
    for cid, members in genuine.items():
        centroid = embs[members].mean(axis=0, keepdims=True)
        sims = cosine_similarity(centroid, embs[unplaced])[0]
        picks = [unplaced[k] for k, s in enumerate(sims) if s > AFFILIATE_THRESHOLD]
        if picks:
            candidates[cid] = picks
    return candidates


def _audit_affiliates(genuine: Dict[int, List[int]], candidates: Dict[int, List[int]],
                       parent_names: Dict[int, str], analyst_role: str) -> Tuple[Dict[int, List[int]], List[Tuple[str, str]]]:
    """Test each candidate ONE AT A TIME against its already-confirmed group
    (existing members + just that one parent per prompt), instead of
    re-auditing a reshuffled batch of several new candidates together.
    Lowering the threshold and re-running _audit_outliers on the combined
    batch was tried first: it destabilized the LLM's outlier judgment and
    dropped 5 previously-confirmed members while only adding 2 new ones — a
    net loss, purely from batch-composition noise, not new information. Here
    the established members always outnumber the single trial candidate, so
    their consensus can't flip, and a rejection only ever discards the one
    candidate under test, never an already-confirmed member."""
    trials: List[Tuple[int, int]] = []
    prompts = []
    for cid, cand_list in candidates.items():
        existing_names = [parent_names[m] for m in genuine[cid]]
        for cand in cand_list:
            prompts.append(_outlier_prompt(existing_names + [parent_names[cand]], analyst_role))
            trials.append((cid, cand))

    if not prompts:
        return genuine, []

    log.info(f"Testing {len(prompts)} affiliate candidate(s) against established group(s)...")
    responses = llm_client.generate_batch(prompts, max_tokens=80, desc="Affiliate fit check")

    updated = {cid: list(members) for cid, members in genuine.items()}
    accepted: List[Tuple[str, str]] = []
    for (cid, cand), raw in zip(trials, responses):
        outliers = set(parse_llm_list(raw))
        cand_name = parent_names[cand]
        if cand_name in outliers:
            continue
        updated[cid].append(cand)
        accepted.append((cand_name, cid))
    return updated, accepted


# Same shape as nested.py's own macro naming/description prompts (its
# "Batch 5 & 6", lines ~296-317) — reused one level up. There the input is
# a parent's own sub-categories' name+description pairs; here it's a
# grandparent's own member PARENTS' existing name+description pairs. No new
# schema, no key_features/notable_details.
_GRANDPARENT_NAME_PROMPT = """\
You are organizing a {organizer_role} enterprise knowledge base.
Analyze the following group of top-level categories and their descriptions to find the common ground:

{context}

Provide a broad, overarching Grandparent Category Name (max 4 words) that accurately encompasses ALL of these categories.
IMPORTANT RULES:
- Use descriptive, functional terms (e.g., 'Financial Operations', 'Infrastructure & Security', 'Claims Processing').
- DO NOT use specific company, vendor, or brand names.
- Reply ONLY with the name, no quotes."""

_GRANDPARENT_DESC_PROMPT = """\
You are organizing a {organizer_role} enterprise knowledge base.
Analyze the following group of top-level categories and their descriptions:

{context}

Write a comprehensive 2-sentence Grandparent Category Description that summarizes the overarching theme connecting all of these categories. Focus on the shared operational, technical, or business goals.
Reply ONLY with the description text, no preamble."""

# Tried: merging member parents' own hierarchy_summarizer.py detail
# (concrete named features) into the stored doc text instead of the fresh
# abstract 2-sentence description, on the theory that concrete text competes
# better in retrieval. Measured on the 4 relationship queries that already
# work: 3 of 4 got WORSE (one -1.6 pts), 1 marginally better. Reverted —
# see conversation for the full readout. Note this only ever affects the
# cross-encoder rerank stage, not whether the doc gets selected at all
# (selection runs on the embedded short description, unchanged either way).


def main():
    parents, taxonomy_data = _load_parents()
    parent_names = {p["idx"]: p["name"] for p in parents}
    log.info(f"Loaded {len(parents)} parents")

    embs = _embed_parents(parents)
    parent_graph = _build_parent_graph(embs)
    log.info(f"Parent graph: {parent_graph.number_of_edges()} edges (threshold={PARENT_THRESHOLD})")

    partition = community_louvain.best_partition(parent_graph) if parent_graph.number_of_edges() > 0 \
        else {i: i for i in parent_names}
    clusters: Dict[int, List[int]] = {}
    for node_id, comm_id in partition.items():
        clusters.setdefault(comm_id, []).append(node_id)

    multi_before = {c: m for c, m in clusters.items() if len(m) > 1}
    log.info(f"Louvain: {len(clusters)} grandparent groups, {len(multi_before)} multi-parent, "
             f"{len(clusters) - len(multi_before)} singleton")

    analyst_role, _ = _get_domain_profile(taxonomy_data)
    clusters = _audit_outliers(clusters, parent_names, analyst_role)
    multi_after = {c: m for c, m in clusters.items() if len(m) > 1}
    log.info(f"After outlier audit: {len(multi_after)} multi-parent group(s) remain")

    # Drop groups that are just nested.py's own naming-collision artifact —
    # e.g. "General IT Operations", "General IT Operations (2)", ... — where
    # EVERY member reduces to the same base name once the "(N)" disambiguator
    # nested.py appends on a repeated LLM name is stripped. A group like this
    # isn't a real family; it's the same generic catch-all bucket name having
    # been independently assigned to many unrelated Louvain clusters. No new
    # schema needed to catch this — just a string check on names already in
    # hand, done before spending any naming/description LLM calls on it.
    _NUM_SUFFIX = re.compile(r"\s*\(\d+\)\s*$")
    genuine, dropped = {}, []
    for cid, members in multi_after.items():
        base_names = {_NUM_SUFFIX.sub("", parent_names[m]).strip() for m in members}
        if len(base_names) == 1:
            dropped.append([parent_names[m] for m in members])
        else:
            genuine[cid] = members
    multi_after = genuine

    # Widen against already-confirmed groups only (see _find_affiliate_candidates
    # / _audit_affiliates docstrings) — a stable alternative to re-clustering
    # everything at a lower threshold, which was tried and reverted (see
    # PARENT_THRESHOLD comment above).
    placed_ids = {m for members in multi_after.values() for m in members}
    affiliate_candidates = _find_affiliate_candidates(embs, multi_after, placed_ids)
    if affiliate_candidates:
        multi_after, accepted = _audit_affiliates(multi_after, affiliate_candidates, parent_names, analyst_role)
    else:
        accepted = []
    if accepted:
        for cand_name, cid in accepted:
            log.info(f"Affiliate accepted: '{cand_name}' -> group {cid}")

    for cid, members in sorted(multi_after.items(), key=lambda x: -len(x[1])):
        print(f"  group {cid} ({len(members)}): {[parent_names[m] for m in members]}")
    if dropped:
        print(f"Dropped {len(dropped)} naming-collision group(s) (all members share one base name):")
        for names in dropped:
            print(f"  ({len(names)}) {names[0]} ... {names[-1]}")

    # organizer_role mirrors nested.py's ORGANIZER_ROLE (domain phrasing for
    # the naming/description prompts) — analyst_role from _get_domain_profile
    # serves the same purpose here without a second context_profiler lookup.
    organizer_role = analyst_role

    jobs = []
    for cid, members in multi_after.items():
        context = "\n".join(
            f"- {parent_names[m]}: {taxonomy_data['taxonomy'][m].get('parent_category_description','')}"
            for m in members
        )
        jobs.append({
            "cid": cid, "members": members,
            "name_prompt": _GRANDPARENT_NAME_PROMPT.format(organizer_role=organizer_role, context=context),
            "desc_prompt": _GRANDPARENT_DESC_PROMPT.format(organizer_role=organizer_role, context=context),
        })

    log.info(f"Generating {len(jobs)} grandparent name(s) + description(s)...")
    name_responses = llm_client.generate_batch([j["name_prompt"] for j in jobs], max_tokens=15, desc="Grandparent naming")
    desc_responses = llm_client.generate_batch([j["desc_prompt"] for j in jobs], max_tokens=60, desc="Grandparent describing")

    results = []
    seen_names = {}
    for job, n_resp, d_resp in zip(jobs, name_responses, desc_responses):
        gp_name = n_resp.replace('"', '').replace('\n', '').strip()
        if len(gp_name) > 50 or not gp_name:
            gp_name = "Related Enterprise Systems"
        if gp_name in seen_names:
            seen_names[gp_name] += 1
            gp_name = f"{gp_name} ({seen_names[gp_name]})"
        else:
            seen_names[gp_name] = 1

        gp_desc = d_resp.replace('"', '').replace('\n', ' ').strip()

        results.append({
            "parent_category_name":        gp_name,
            "parent_category_description": gp_desc,
            "member_parents": [taxonomy_data["taxonomy"][m] for m in job["members"]],
        })

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"\nWrote {len(results)} grandparent group(s) → {OUT_PATH}")
    for r in results:
        member_names = [m["parent_category_name"] for m in r["member_parents"]]
        print(f"\n--- {r['parent_category_name']} ---")
        print(r["parent_category_description"])
        print(f"Members: {member_names}")


if __name__ == "__main__":
    main()
